### ISSUE TITLE
Hengshuang new result

### ISSUE THREAD

**Issue by yuchenlichuck** [qq456cvb/Point-Transformers#13]
```
batch_size: 32
epoch: 500
learning_rate: 0.0005
gpu: 0
num_point: 1024
optimizer: Adam
weight_decay: 0.0001
normal: true
model:
  nneighbor: 16
  nblocks: 4
  transformer_dim: 512
  name: Hengshuang
```
Best Instance Accuracy: 0.917067, Class Accuracy: 0.893971
